### ISSUE TITLE
Não funciona em MacOS Catalina

### ISSUE THREAD

**Issue by wscardua** [totvs/tir#373]
Quando executado um teste simples em MacOS não funciona, já em ambiente Windows funciona

MacOS Catalina 10.15.5

>>print(sys.platform)
>>darwin

```
`/Users/WilliamSca/TIR-Protheus/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py:50: DeprecationWarning: use options instead of chrome_options
  warnings.warn('use options instead of chrome_options', DeprecationWarning)
Warning log_error Wasn't possible execute Start() method: 'drivers\\windows\\chromedriver.exe' executable needs to be in PATH. Please see https
Warning Log Error save_screenshot exception 'WebappInternal' object has no attribute 'driver'
Log file created successfully: Log\MacBook-Pro-de-William.local\root_e8a5a6c09cf84a899aa27be9199c2142_auto.csv
Warning Log Error Close 'WebappInternal' object has no attribute 'driver'
Warning Log Error Close 'WebappInternal' object has no attribute 'driver'
E
======================================================================
ERROR: setUpClass (__main__.MATA010)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/WilliamSca/Projetos Python/TIR-Protheus/teste.py", line 8, in setUpClass
    inst.oHelper = Webapp()
  File "/Users/WilliamSca/TIR-Protheus/lib/python3.7/site-packages/tir/main.py", line 21, in __init__
    self.__webapp = WebappInternal(config_path, autostart)
  File "/Users/WilliamSca/TIR-Protheus/lib/python3.7/site-packages/tir/technologies/webapp_internal.py", line 89, in __init__
    self.log_error(message)
  File "/Users/WilliamSca/TIR-Protheus/lib/python3.7/site-packages/tir/technologies/webapp_internal.py", line 4825, in log_error
    self.assertTrue(False, log_message)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 705, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : setUpClass - Wasn't possible execute Start() method: 'drivers\\windows\\chromedriver.exe' executable needs to be in PATH. Please see https

----------------------------------------------------------------------`
```
![Captura de Tela 2020-07-10 às 15 27 43](https://user-images.githubusercontent.com/47982596/87186539-0b76cb00-c2c2-11ea-9e22-0a28d46f9504.png)

**Comment by renanllisboa** [comment]
Bom dia,

O TIR não está homologado para uso no MacOS.

Atenciosamente
